[package]
name = "hueston"
version = "0.1.0"
authors = ["SplittyDev <splittydev@protonmail.com>"]
edition = "2018"

[dependencies]
ssdp = "0.7.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde-xml-rs = "0.2.1"
serde_json = "1.0.33"
reqwest = "0.9.5"
maplit = "1.0.1"